# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mymodelrelated',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
