# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180627_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='date_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
